name: 'Build Chainlink'

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  build-chainlink:
    runs-on: buildjet-2vcpu-ubuntu-2004
    environment: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build chainlink image
        uses: ./.github/actions/build-publish-chainlink
        with:
          publish: false
          image-name: test-choinlonk
          ecr-registry: ${{ secrets.AWS_ECR_URL }}
